from langchain_groq import ChatGroq

from app.agents.prompts import REVIEW_AGENT_PROMPT_TEMPLATE, REVIEW_STATE_TEMPLATE
from app.agents.state import AgentState
from app.config.settings import settings
from app.utils.logger import logger


class ReviewGenerationAgent:
    """Specialist Agent that transforms technical specifications into an in-depth product review."""

    def __init__(self):
        self.llm = ChatGroq(
            model=settings.GROQ_MODEL,
            api_key=settings.GROQ_API_KEY,
            temperature=0.3,
            streaming=True,
        )

        self.prompt = REVIEW_AGENT_PROMPT_TEMPLATE


    def stream_review(
        self,
        spec_dossier: str,
        focus_instructions: str = "General Consumer Review",
    ):
        """Streams review tokens in real-time as they are generated by Groq."""
        logger.info("ReviewGenerationAgent: Streaming review tokens...")
        chain = self.prompt | self.llm
        for chunk in chain.stream(
            {
                "spec_dossier": spec_dossier,
                "focus_instructions": focus_instructions,
            }
        ):
            if chunk.content:
                yield str(chunk.content)

    def run_state(self, state: AgentState) -> AgentState:
        """Generate a grounded final response from the specification-agent state."""
        dossier = state.get("technical_dossier") or state.get("specs_result", "")
        if state.get("error") and not dossier:
            return {**state, "review": f"Unable to retrieve specifications: {state['error']}"}
        try:
            chain = REVIEW_STATE_TEMPLATE | self.llm
            result = chain.invoke(
                {
                    "query": state.get("query", ""),
                    "specs_result": dossier or "No verified specifications were found.",
                    "review_focus": state.get("review_focus", "General Consumer Review"),
                }
            )
            return {**state, "review": str(result.content)}
        except Exception as error:
            logger.exception("Review agent failed")
            return {**state, "review": "Unable to generate a review from the retrieved specifications.", "error": str(error)}