from langchain_core.prompts import ChatPromptTemplate
from langchain_groq import ChatGroq
from app.config.settings import settings
from app.utils.logger import logger
from app.agents.prompts import REVIEW_AGENT_PROMPT_TEMPLATE


class ReviewGenerationAgent:
    """Specialist Agent that transforms technical specifications into an in-depth product review."""

    def __init__(self):
        self.llm = ChatGroq(
            model=settings.GROQ_MODEL,
            api_key=settings.GROQ_API_KEY,
            temperature=0.3,
            streaming=True,
        )

        self.prompt = REVIEW_AGENT_PROMPT_TEMPLATE


    def stream_review(self, spec_dossier, focus_instructions= "General Consumer Review"):
        """Streams review tokens in real-time as they are generated by Groq."""
        logger.info("ReviewGenerationAgent: Streaming review tokens...")
        chain = self.prompt | self.llm
        for chunk in chain.stream(
            {
                "spec_dossier": spec_dossier,
                "focus_instructions": focus_instructions,
            }
        ):
            if chunk.content:
                yield str(chunk.content)